
markdown_extensions:
- admonition

nav:
- Overview: index.md
- getting_started.md
- Custom Resources:
  - Virtual Machines (QEMU): 
    - VirtualMachine: crds/virtualmachine.md
    - ManagedVirtualMachine: crds/managedvirtualmachine.md
    - VirtualMachineSet: crds/virtualmachineset.md
    - VirtualMachineSnapshot: crds/virtualmachinesnapshot.md
    - VirtualMachineSnapshotPolicy: crds/virtualmachinesnapshotpolicy.md
  - Containers (LXC): 
    - Container: crds/container.md
  - Storage: 
    - Storage: crds/storagedownloadurl.md
  - Certificates:
    - CustomCertificate: crds/customcertificate.md
- metrics.md
- contributing.md
- roadmap.md
- Releases ⧉: https://github.com/alperencelik/kubemox/releases

repo_url: https://github.com/alperencelik/kubemox 
site_name: Kubemox - Proxmox Operator for Kubernetes
strict: true
theme:
  favicon: images/kubemox.jpg
  font:
    text: Work Sans
  logo: images/kubemox.jpg
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: indigo # deep orange? 
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: indigo # deep orange?
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

plugins: 
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true