apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubemox-monitor
  labels:
    prometheus: kube-prom-stack
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubemox
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - default
