---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubemox 
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - managedvirtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - managedvirtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - managedvirtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - virtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
