# permissions for end users to edit virtualmachinesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualmachineset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubemox
    app.kubernetes.io/part-of: kubemox
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachineset-editor-role
rules:
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - virtualmachinesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - virtualmachinesets/status
  verbs:
  - get
