apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    app.kubernetes.io/name: virtualmachine
    app.kubernetes.io/instance: virtualmachine-sample
    app.kubernetes.io/part-of: kubemox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubemox
  name: virtualmachine-sample
spec:
  # TODO(user): Add fields here
