apiVersion: proxmox.alperen.cloud/v1alpha1
kind: CustomCertificate
metadata:
  name: customcertificate-sample
spec:
  nodeName: "lowtower"
  certManagerSpec:
    commonName: "proxmox.alperen.cloud"
    dnsNames:
      - "proxmox.alperen.cloud"
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: acme-issuer 
    secretName: proxmox-alperen-cloud-tls
    usages: 
      - client auth
      - server auth
  proxmoxCertSpec: 
    nodeName: "lowtower"
    force: true
    restartProxy: true